name = "slipradiosite"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "SHOWS"
id = "9470153371854d02bc402a79f8d0faa0"

[[r2_buckets]]
binding = "THUMBNAILS"
bucket_name = "slip-radio-thumbnails"

[vars]
NOW_PLAYING_API_URL = "https://a8.asurahosting.com/api/nowplaying/slip_radio"
